name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm run eslint
      - name: build
        run: npm run build
      - name: run unit tests
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Deploy to Render
        if: ${{ (github.event_name == 'push') && !(contains(github.event.head_commit.message, '#skip')) }}
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false
      - name: Send error notification to Discord if failure
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: Build failed
          status: Failure
          color: 0xFF0000
          description: commit ${{ github.event.commits.url }} by ${{ github.triggering_actor }} broke the build :(

  tag_release:
    if: ${{ (github.event_name == 'push') && !(contains(github.event.head_commit.message, '#skip')) }}
    runs-on: ubuntu-latest
    needs: [build_and_deploy]
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.70.0
        if: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Send success notification to Discord
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          content: "A new version of Pokedex was deployed"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
