name: Testing stuff

env:
  WILL_SKIP: ${{ contains(join(github.event.commits.message), '#skip') }}

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: test condition to false
        if: ${{ github.env.WILL_SKIP == 'false' }}
        run: echo "WILL_SKIP == false"
      - name: test condition to true
        if: ${{ github.env.WILL_SKIP == 'true' }}
        run: echo "WILL_SKIP == true"
