name: Testing commit message stuff

env:
  WILL_SKIP: ${{ (github.event_name == 'push') && (contains(github.event.head_commit.message, '#skip')) }}

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.head_commit.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: test conditional deployment
        if: ${{ (github.event_name == 'push') && !(contains(github.event.head_commit.message, '#skip')) }}
        run: echo "does not contain the magic word to skip"
